services:
  - type: web
    name: personal-blog
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CACHE_DATABASE_URL
        sync: false
      - key: QUEUE_DATABASE_URL
        sync: false
      - key: CABLE_DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_LEVEL
        value: info
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
